### ISSUE TITLE
Modded Enchants

### ISSUE THREAD

**Issue by O13SC3N3** [mc-jt9/Wards#1]
So may be a stupid question, haven't read it on the wiki unless im blind. But does this work with ANY enchanted book with any effect from any mod?

**Comment by OrderedChaos-Dev** [comment]
No, unfortunately the function of enchantments are bits of code found all over the place, so I have to write my own effect for each enchantment. I personally don't use enchantment mods in my game, so I'm not familiar with the popular ones right now. If you have suggestions for compatibility with modded enchants, please let me know.

**Comment by TheDeviantCrafter** [comment]
[CoFH Core's enchantments](https://teamcofh.com/docs/cofh-core/) are pretty neat.

Quite a few mods add soulbound, which all work in roughly the same way. An item enchanted with soulbound isn't lost on death.

Thaumcraft adds some useful enchantments, but they would be tricky to implement. They're complex and hooked into Thaumcraft mechanics.

**Comment by OrderedChaos-Dev** [comment]
I'll see what I can do about those. For Thaumcraft, confession time: I've never played with that mod, but I'll see how I can work with its enchantments.

**Comment by Avadonia** [comment]
I personally like https://minecraft.curseforge.com/projects/so-many-enchantments, it also have bad enchant which would be good debuff ward :)

**Comment by OrderedChaos-Dev** [comment]
I'll look into it, thanks!

**Comment by jonathantai9** [comment]
I've made a to-do list of mods: #5

**Comment by OrderedChaos-Dev** [comment]
I've made a to-do list for mods to support: #5
