### ISSUE TITLE
Dungeon loot doesn't generate

### ISSUE THREAD

**Issue by D-Bigboy-302** [mc-jt9/Wards#13]
Mod Version: wards-1.15.2-1.4.0.jar
Forge Version: 1.15.2-forge-31.2.31

The mods I have that add loot:
Charm - 1.15.2-1.5.7
Craft and Hunt - V1.1.0_MC_1.15.2
Dungeon Crawl - 1.15.2-1.6.3
Enigmatic Legacy - 1.7.0
First Aid - 1.8.2
Rings of Ascension - 1.15.2-1.5.1
Scaling Health - 1.15.2-3.0.7
Upgrade Aquatic - 1.15.2-1.7.1

An issue of this has been opened and resolved in Rings Of Ascension. I believe it had something to do with Charm loot tables.

**Comment by Carro1001** [comment]
Can confirm, it's still an issue

**Comment by OrderedChaos-Dev** [comment]
Just seeing this now, because I forgot I had mods to develop.
The mod only modifies shipwreck and buried treasure loot by adding a loot entry, not replacing anything, so it's one of the other mods listed that's causing the issue.
