### ISSUE TITLE
[Request] Backport 1.15 features to 1.12

### ISSUE THREAD

**Issue by democat3457** [mc-jt9/Wards#14]
Would be greatly appreciated if you can. That custom list of placeable items would be nice to have.

**Comment by Kompreya** [comment]
Agreed! Would especially love the configurable ward fuels for 1.12

**Comment by OrderedChaos-Dev** [comment]
I don't have time to support multiple versions, sorry, so I have to rule out 1.12 support.

**Comment by CalaMariGold** [comment]
Are you open to pull requests for 1.12.2 that add these features?

**Comment by CalaMariGold** [comment]
Bump @OrderedChaos-Dev

**Comment by OrderedChaos-Dev** [comment]
Sorry, I didn't see this comment. You're welcome to backport it and open a pull request.
