### ISSUE TITLE
Admin Stand / Creative

### ISSUE THREAD

**Issue by StoneLegion** [mc-jt9/Wards#2]
Not sure if this would be out of the scope of the mod but it be nice if we could have an admin/creative stand that could be used for say Spawn. Maybe besides having unlimited fuel only an op can remove / add the enchantment book to the stand. Breaking it be nice too but honestly that can be dealt with normal spawn protection. But I do fear that vanilla might bypass Interaction for the books. 

Thanks

**Comment by OrderedChaos-Dev** [comment]
I'll be putting in more config options to make the wards more configurable.

**Comment by OrderedChaos-Dev** [comment]
I've added admin mode in the latest update. Just right-click the ward with a command block and it should only allow OPed players to do stuff with it.

**Comment by StoneLegion** [comment]
Awesome thanks :)
