### ISSUE TITLE
Crash with mod Enchantments

### ISSUE THREAD

**Issue by Zygus42** [mc-jt9/Wards#3]
wards-1.0
forge-1.12.2-14.23.5.2806-installer-win

I put a modded book of Holding 4 (from Thermal Expansion) on the stand, game crashed.  I have no problem with the modded books not working, but shouldn't crash the game.

[crash-2019-01-19_13.05.36-server.txt](https://github.com/mc-jt9/Wards/files/2775184/crash-2019-01-19_13.05.36-server.txt)

**Comment by OrderedChaos-Dev** [comment]
I'll look into it.

**Comment by OrderedChaos-Dev** [comment]
Should be fixed in 1.1. Any modded enchantments not yet supported will just default to sharpness.
