### ISSUE TITLE
[feature request] Tooltip

### ISSUE THREAD

**Issue by Zygus42** [mc-jt9/Wards#4]
A small tooltip on the stand item would be great.  Perhaps something like:  "Place Enchanted Book on stand + right click lapis on it to fuel the ward".  Not everyone playing is going to go and look up the wiki to find out what it does.

**Comment by OrderedChaos-Dev** [comment]
Tooltip sounds like a good idea.

**Comment by OrderedChaos-Dev** [comment]
Tooltip added in 1.1
