### ISSUE TITLE
List of mods to support!

### ISSUE THREAD

**Issue by OrderedChaos-Dev** [mc-jt9/Wards#5]
Here's a list of the mods to add support for:

- [ ] [Quark's ancient tomes](https://minecraft.curseforge.com/projects/quark)
- [ ] [Thaumcraft](https://minecraft.curseforge.com/projects/thaumcraft)
- [ ] [CoFH Core](https://minecraft.curseforge.com/projects/cofhcore)
- [ ] [So Many Enchantments](https://minecraft.curseforge.com/projects/so-many-enchantments)
- [ ] [Thermal Expansion](https://minecraft.curseforge.com/projects/thermalexpansion)
- [ ] [Living Enchantment](https://minecraft.curseforge.com/projects/living-enchantment)
- [ ] [Enchanting Plus](https://minecraft.curseforge.com/projects/enchanting-plus)

**Comment by OrderedChaos-Dev** [comment]
May 29 update: probably not gonna get to this for a long time lol

**Comment by denzuko** [comment]
+1 for Botania. Wards crashes with floating flowers nearby. Crashlog can be seen at: https://gist.github.com/denzuko/e60cd7f7a6cf9e7da1602ffd49c6389b

**Comment by OrderedChaos-Dev** [comment]
outdated
