### ISSUE TITLE
Duped book image on the ground on removal

### ISSUE THREAD

**Issue by VallenFrostweaver** [mc-jt9/Wards#7]
Wards: 1.1
Forge: 14.23.5.2781
I placed a Bane of Arthropods I book on the ward pedestal and then right clicked to remove the book and 2 pop off the ward. One is real and the other is a fake book that sits there and is non-interactable.

EDIT: Right clicking another magic book onto the ward pedestal creates a dupe as well.

**Comment by OrderedChaos-Dev** [comment]
I'll check it out
