### ISSUE TITLE
Drastic FPS drop

### ISSUE THREAD

**Issue by VallenFrostweaver** [mc-jt9/Wards#8]
Wards: 1.1
Forge: 14.23.5.2781
Placing a Ward (no book or anything) causes a drop of 50% in my FPS. Adding more wards appropriately spaced, equipped with books, and lapis causes even more FPS drop (75%). Tried Foamfix and BetterFPS just in case it was me but no change.

**Comment by OrderedChaos-Dev** [comment]
I'll check it out

**Comment by OrderedChaos-Dev** [comment]
So I made it check the 15 block radius (~27000 blocks) once every 5 seconds instead of 20 times per second so that should help. Hopefully it should solve your fps problem
