### ISSUE TITLE
Burn enchanted books as fuel 

### ISSUE THREAD

**Issue by TheDeviantCrafter** [mc-jt9/Wards#9]
This mod was created because someone had too many enchanted books. Using books as fuel would let players burn through their chest of garbage enchants quite a bit faster.

I suggest a new block that destroys enchanted books to give Enchanted Paper. These are scraps of paper which can be used to power the ward.

**Comment by OrderedChaos-Dev** [comment]
I really like that idea!

**Comment by OrderedChaos-Dev** [comment]
Added in 1.3!
